# investor_config.py

INVESTOR_CONFIG = {
    "real_estate": {
        "label": "Real Estate & Urban Development",
        "primary": [
            "Total_Population",
            "Population_Growth_Rate",
            "Median_Age",
            "Real_GDP_per_Capita_USD",
            "Real_GDP_Growth_Rate_percent",
            "Unemployment_Rate_percent",
            "internet_users_total",
            "broadband_fixed_subscriptions_total",
            "mobile_cellular_subscriptions_total",
        ],
        "secondary": [
            "Net_Migration_Rate",
            "Youth_Unemployment_Rate",
            "Population_Below_Poverty_Line_percent",
            "Public_Debt_percent_of_GDP",
            "Area_Total",
            "Land_Area",
            "Agricultural_Land",
            "Irrigated_Land",
            "roadways_km",
            "railways_km",
            "airports_paved_runways_count",
        ],
        "filters": [
            "Real_GDP_per_Capita_USD",
            "Real_GDP_Growth_Rate_percent",
            "Population_Growth_Rate",
            "Youth_Unemployment_Rate",
        ],
    },

    "agriculture": {
        "label": "Agriculture & Agri-business",
        "primary": [
            "Total_Population",
            "Population_Growth_Rate",
            "Real_GDP_Growth_Rate_percent",
            "Agricultural_Land",
            "Arable_Land (%% of Total Agricultural Land)",
            "Irrigated_Land",
            "electricity_access_percent",
        ],
        "secondary": [
            "Permanent_Crops (%% of Total Agricultural Land)",
            "Permanent_Pasture (%% of Total Agricultural Land)",
            "Area_Total",
            "Land_Area",
            "Water_Area",
            "Exports_billion_USD",
            "Imports_billion_USD",
            "electricity_generating_capacity_kW",
            "roadways_km",
            "railways_km",
            "waterways_km",
        ],
        "filters": [
            "Agricultural_Land",
            "Arable_Land (%% of Total Agricultural Land)",
            "Irrigated_Land",
        ],
    },

    "transport": {
        "label": "Transportation & Logistics",
        "primary": [
            "Total_Population",
            "Real_GDP_PPP_billion_USD",
            "Real_GDP_Growth_Rate_percent",
            "Exports_billion_USD",
            "Imports_billion_USD",
            "airports_paved_runways_count",
            "roadways_km",
            "railways_km",
            "waterways_km",
        ],
        "secondary": [
            "Population_Growth_Rate",
            "Coastline",
            "Land_Boundaries",
            "Area_Total",
            "airports_unpaved_runways_count",
            "heliports_count",
            "gas_pipelines_km",
            "oil_pipelines_km",
            "refined_products_pipelines_km",
            "petroleum_bbl_per_day",
            "refined_petroleum_products_bbl_per_day",
            "refined_petroleum_exports_bbl_per_day",
            "refined_petroleum_imports_bbl_per_day",
        ],
        "filters": [
            "Real_GDP_PPP_billion_USD",
            "Exports_billion_USD",
            "Imports_billion_USD",
        ],
    },

    "telecom": {
        "label": "Telecom & Digital Infrastructure",
        "primary": [
            "Total_Population",
            "Median_Age",
            "Real_GDP_per_Capita_USD",
            "mobile_cellular_subscriptions_total",
            "internet_users_total",
            "broadband_fixed_subscriptions_total",
        ],
        "secondary": [
            "telephone_fixed_subscriptions_total",
            "Population_Growth_Rate",
            "Total_Literacy_Rate",
            "Male_Literacy_Rate",
            "Female_Literacy_Rate",
            "Youth_Unemployment_Rate",
            "Real_GDP_Growth_Rate_percent",
            "Unemployment_Rate_percent",
            "Public_Debt_percent_of_GDP",
            "electricity_access_percent",
            "electricity_generating_capacity_kW",
            "internet_country_code",
        ],
        "filters": [
            "mobile_cellular_subscriptions_total",
            "internet_users_total",
            "broadband_fixed_subscriptions_total",
        ],
    },

    "retail": {
        "label": "Retail & E-commerce",
        "primary": [
            "Total_Population",
            "Population_Growth_Rate",
            "Median_Age",
            "Real_GDP_per_Capita_USD",
            "Real_GDP_Growth_Rate_percent",
            "mobile_cellular_subscriptions_total",
            "internet_users_total",
        ],
        "secondary": [
            "Youth_Unemployment_Rate",
            "Total_Literacy_Rate",
            "Unemployment_Rate_percent",
            "Population_Below_Poverty_Line_percent",
            "Exchange_Rate_per_USD",
            "broadband_fixed_subscriptions_total",
            "electricity_access_percent",
            "roadways_km",
        ],
        "filters": [
            "Real_GDP_per_Capita_USD",
            "Population_Growth_Rate",
            "internet_users_total",
        ],
    },

    "fintech": {
        "label": "Financial Services & Fintech",
        "primary": [
            "Total_Population",
            "Median_Age",
            "Real_GDP_per_Capita_USD",
            "Real_GDP_Growth_Rate_percent",
            "mobile_cellular_subscriptions_total",
            "internet_users_total",
        ],
        "secondary": [
            "Youth_Unemployment_Rate",
            "Total_Literacy_Rate",
            "Male_Literacy_Rate",
            "Female_Literacy_Rate",
            "Unemployment_Rate_percent",
            "Youth_Unemployment_Rate_percent",
            "Population_Below_Poverty_Line_percent",
            "Public_Debt_percent_of_GDP",
            "Exchange_Rate_per_USD",
            "broadband_fixed_subscriptions_total",
            "electricity_access_percent",
        ],
        "filters": [
            "Real_GDP_per_Capita_USD",
            "Youth_Unemployment_Rate",
            "mobile_cellular_subscriptions_total",
            "internet_users_total",
        ],
    },
}
